version: "3"

services:

  api:
    image: chzbrgr71/core-api
    links:
      - core-web
    ports:
      - 5001:5001
    deploy:
      replicas: 3

  web:
    image: chzbrgr71/core-web
    ports:
     - 80:5000
    environment:
      - BACKEND_IP=core-simple_api
      - BACKEND_PORT=5001
      - ORCHESTRATOR=Swarm Mode
    deploy:
      replicas: 6