version: "3"

services:

  core-api:
    image: chzbrgr71/core-api:dcos
    links:
      - core-web
    ports:
      - 5001:5001
    deploy:
      replicas: 3

  core-web:
    image: chzbrgr71/core-web:dcos
    ports:
     - 80:5000
    environment:
      - BACKEND_IP=briarswarmmode.southcentralus.cloudapp.azure.com
      - BACKEND_PORT=5001
      - ORCHESTRATOR=Swarm
    deploy:
      replicas: 5