version: "3"

services:

  core-api:
    image: chzbrgr71/core-api
    links:
      - core-web
    ports:
      - 5001:5001
    deploy:
      replicas: 4

  core-web:
    image: chzbrgr71/core-web
    ports:
     - 80:5000
    environment:
      - BACKEND_IP=briarswarmmode.southcentralus.cloudapp.azure.com
      - BACKEND_PORT=5001
      - ORCHESTRATOR=Swarm Mode
    deploy:
      replicas: 6