apiVersion: v1
kind: Service
metadata:
  name: core-api
  labels:
    app: core-api
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 5001
  clusterIP: 10.0.176.131
  selector:
    run: core-api
---
apiVersion: v1
kind: Service
metadata:
  name: core-web
  labels:
    app: core-web
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
  selector:
    run: core-web
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: core-api
spec:
  replicas: 4
  template:
    metadata:
      labels:
        run: core-api
        app: core-api
    spec:
      containers:
      - name: core-api
        image: briarregistry-microsoft.azurecr.io/chzbrgr71/core-api
        ports:
          - containerPort: 5001
      imagePullSecrets:
        - name: myregistrykey
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: core-web
spec:
  replicas: 5
  template:
    metadata:
      labels:
        run: core-web
        app: core-web
    spec:
      containers:
      - name: core-web
        image: chzbrgr71/core-web
        env:
        - name: BACKEND_IP
          value: "10.0.176.131"
        - name: BACKEND_PORT
          value: "8080"
        - name: ORCHESTRATOR
          value: "Kubernetes"
        ports:
          - containerPort: 5000