apiVersion: v1
kind: Service
metadata:
  name: core-web
  labels:
    app: core-web
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
  selector:
    run: core-web
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: core-web
spec:
  replicas: 5
  template:
    metadata:
      labels:
        run: core-web
        app: core-web
    spec:
      containers:
      - name: core-web
        image: chzbrgr71/core-web:k8s
        env:
        - name: BACKEND_IP
          value: "10.0.176.131"
        - name: BACKEND_PORT
          value: "8080"
        ports:
          - containerPort: 5000