apiVersion: v1
kind: Service
metadata:
  labels:
    app: core-sql
    component: core-sql
  name: core-sql
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
      name: core-sql-port
  selector:
    app: core-sql
    component: core-sql